// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
//
// Self-hosted Postgres (Docker): DATABASE_URL and DIRECT_URL both point at
// the same database — see .env.example / docker-compose.yml.
// To run migrations against production, set DATABASE_URL to that server's
// value first (see docker-compose.app.yml for how the app container does
// this), then: npx prisma migrate deploy
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "tsx prisma/seed.ts",
  },
  datasource: {
    url: process.env["DATABASE_URL"],
  },
});
