// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
//
// Supabase: set DATABASE_URL (pooled) + DIRECT_URL in .env.
// Migrations must use the direct URL:
//   set -a && source .env && DATABASE_URL="$DIRECT_URL" npx prisma migrate deploy
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "tsx prisma/seed.ts",
  },
  datasource: {
    url: process.env["DATABASE_URL"],
    directUrl: process.env["DIRECT_URL"],
  },
});
